### ISSUE TITLE
Experiment with `-XX:NativeMemoryTracking` to check for memory leaks

### ISSUE THREAD

**Issue by lptr** [gradle/native-platform#125]
This feature of the JVM could be used to check if we are leaking memory:

https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr007.html

We could get a baseline, start some watchers, handle some events, tear down the watchers, and then check the diff.

(Thanks @paplorinc for the tip!)

**Comment by wolfs** [comment]
The documentation states
> Since NMT doesn't track memory allocations by non-JVM code, you may have to use tools supported by the operating system to detect memory leaks in native code.

I wonder what kind of leaks we would find...

**Comment by lptr** [comment]
Ah, that's too bad. :(

**Comment by paplorinc** [comment]
Thanks for checking @wolfs , that's what we've assumed anyway.
https://static.rainfocus.com/oracle/oow18/sess/1524505564465001W0mS/PF/Troubleshooting_native_memory_leaks_1540301908390001k6DR.pdf, page 31 contains a few options for tracking memory that's allocated off JVM.
