### ISSUE TITLE
Update native log level automatically

### ISSUE THREAD

**Issue by lptr** [gradle/native-platform#128]
Currently the log level for the watcher `Logger` is stored on the native side upon initializing the logging. However, in a Java application, the log level can change. Indeed, in `gradle/gradle` we'd like to let the user alter the log level for file watching.

Ideally, we should query the log level whenever we try to log any message, but this would be prohibitively expensive; one of the two goals of checking the log level on the native side is to avoid having to call through JNI (the other being to avoid the cost of `sprintf()`).

We could do an alternative, and cache the log level on the native side with a relatively short timeout, such as one second. This way we'd update the native log level frequently enough, but wouldn't incur the cost too often.

If we did this the logging would not need to be initialized, making the code simpler.

**Comment by wolfs** [comment]
Note that the log level for JUL is always set to `FINE` from the Gradle side, even though we filter out messages later on when using the SLF4J bridge: https://github.com/gradle/gradle/blob/9aba91121c2a88d158ac8d60ac692ece78a749f7/subprojects/logging/src/main/java/org/gradle/internal/logging/source/JavaUtilLoggingSystem.java#L36-L53

Without fixing this, we won't have fewer logging.

**Comment by lptr** [comment]
I'm talking to @jjohannes about reverting that. Running a build now to see what breaks: https://github.com/gradle/gradle/pull/12461

**Comment by lptr** [comment]
If that doesn't work, we can opt to use SLF4J. If we do that, though, then I think we'll need to slice off file watching into its own JAR with its own dependencies. Or make logging to SLF4J a feature of `native-platform`. Either way it's a significant amount of work I don't want to undertake now.

**Comment by lptr** [comment]
I've ran a very scientific (not) test on Linux, registering and immediately unregistering the same directory 10k times. That's 20k JNI calls, and the same number of scheduling on the thread, so there's plenty of overhead (that we'll get rid of when using batched APIs in #129). But still, whether or not we were calling back to Java to log a line made a big difference.

- with logging: 1.992 sec
- without logging: 0.446 sec

That's ~4.5x slower when logging is enabled.

**Comment by lptr** [comment]
The problem in `gradle/gradle` should now be fixed (unless we see some flakiness reappear due to the change in gradle/gradle#12461).

**Comment by lptr** [comment]
If we do this we should also check that we don't do expensive calculations before calling something like `log_fine()`. Adding something like `log_enabled(LOG_LEVEL_FINE)` could be necessary.

**Comment by lptr** [comment]
Fixed via #150.
