### ISSUE TITLE
Allow timeouts to be configured for file watching

### ISSUE THREAD

**Issue by lptr** [gradle/native-platform#183]
We should make the following timeouts configurable:

- [x] ~~ALL: event offering timeout before we declare an `OVERFLOWED`~~
- [x] ALL: termination timeout
- [x] Windows: execute on thread timeout

The basic option is to pass them in the `WatcherBuilder`, e.g. `WatcherBuilder.withEventProcessingTimeout(5, SECONDS)`.

For termination we could also use this, or we switch away from `close()` and instead introduce something like `terminateAndWaitFor(5, SECONDS)`. Another option is to implement something similar to what `ExecutorService` does with `shutdown()` + `awaitTermination()`.

**Comment by wolfs** [comment]
I think there shouldn't be an `event offering timeout` at all - we should always send the overflow event.

**Comment by lptr** [comment]
We don't have an event offering timeout anymore, and the other timeouts can now be configred.
