### ISSUE TITLE
Sign released artifacts

### ISSUE THREAD

**Issue by lptr** [gradle/native-platform#267]
So that they can be consumed easily with dependency verification.

**Comment by lptr** [comment]
@melix would singing the `native-platform` artifacts allow us to remove the `<component group="net.rubygrapefruit" name="file-events" version="0.22-milestone-14">` etc. lines from `verification-metadata.xml` in Gradle's build, and simplify upgrades? If so, I'd say we should do this soon.

**Comment by melix** [comment]
Yes it would simplify the upgrades: you wouldn't need to update the file after each upgrade as long as the key used to sign the artifacts doesn't change.
