### ISSUE TITLE
Handle Java exceptions happening in watcher callbacks

### ISSUE THREAD

**Issue by lptr** [gradle/native-platform#66]
When an exception happens while executing a file system event watcher callback, it should be handled.

----
/cc @gradle/build-cache

**Comment by lptr** [comment]
OK, but how? We can recognize the Java exception itself easily via JNI, but what can we do about it in the native thread?

We could stop the thread itself, but is that a good way to handle the problems?

Swallowing the exception is another option, though this could lead to problems going unnoticed. That could have some devastating effect.

**Comment by wolfs** [comment]
`stopWatching` could rethrow the exception. I think that would probably be the best course of action. WDYT?

**Comment by lptr** [comment]
What if multiple exceptions happen while watching? Would we somehow correlate the exceptions to the paths being reported when they happened?

**Comment by lptr** [comment]
This is now handled.
