### ISSUE TITLE
Handle timeouts in file watchers

### ISSUE THREAD

**Issue by lptr** [gradle/native-platform#98]
Currently we are waiting on things forever in several places in the file watcher code. We should stop after a few seconds probably and break instead.

**Comment by lptr** [comment]
We could also think about adding something like a `AbstractServer::forceTerminate()` method to kill the thread without freeing the watchers if some timeout is elapsed.

**Comment by lptr** [comment]
I've looked at each place where we sleep/wait with a timeout, and I think they all make sense except for one on Linux.

### macOS

Does not require waiting anywhere.

### Windows

https://github.com/gradle/native-platform/blob/990066ad11d8dd6faca17b2430d36a9bda607a5b/src/file-events/cpp/win_fsnotifier.cpp#L288-L290

Here we wait infinitely for either a user APC or a file system event to come in. I don't think we can do anything else here. Even if we woke up every five seconds, what could we check? `terminated` is set in a user APC-triggered command.

https://github.com/gradle/native-platform/blob/990066ad11d8dd6faca17b2430d36a9bda607a5b/src/file-events/cpp/win_fsnotifier.cpp#L63-L65

and

https://github.com/gradle/native-platform/blob/990066ad11d8dd6faca17b2430d36a9bda607a5b/src/file-events/cpp/win_fsnotifier.cpp#L315-L319

In these places we don't really wait, as the timeout is set to `0`.

### Linux

https://github.com/gradle/native-platform/blob/990066ad11d8dd6faca17b2430d36a9bda607a5b/src/file-events/cpp/linux_fsnotifier.cpp#L99-L109

This is the only place where we block with a timeout. It gets called from two places:

https://github.com/gradle/native-platform/blob/990066ad11d8dd6faca17b2430d36a9bda607a5b/src/file-events/cpp/linux_fsnotifier.cpp#L89-L93

This is in the run loop and is very similar to the Windows situation. Even if we woke up after every few seconds, what would we do? So I think waiting forever is the right option here.

https://github.com/gradle/native-platform/blob/990066ad11d8dd6faca17b2430d36a9bda607a5b/src/file-events/cpp/linux_fsnotifier.cpp#L266-L269

Here we currently wait for a second, but it doesn't seem to be necessary. Removing timeout: https://github.com/gradle/native-platform/pull/151

**Comment by lptr** [comment]
There are also the two places where we wait for:

https://github.com/gradle/native-platform/blob/master/src/file-events/cpp/generic_fsnotifier.cpp#L61-L64

The background thread to start up, and:

https://github.com/gradle/native-platform/blob/master/src/file-events/cpp/generic_fsnotifier.cpp#L93-L95

Where we wait for the command to be executed on the thread.

Here we should be using some sane timeout instead of waiting indefinitely.

**Comment by lptr** [comment]
Added a one-second timeout for thread operations: https://github.com/gradle/native-platform/pull/152

**Comment by lptr** [comment]
PRs merged. @wolfs do you think we need to do anything more or shall we close this?

**Comment by wolfs** [comment]
I think we are good now.
